<?php
/**
 * Countries data for phone code and country dropdowns
 * Sorted: Malawi first, then African countries, then rest of world alphabetically
 */
$countries = [
    // --- Malawi (hotel location, default) ---
    ['name' => 'Malawi',                    'iso2' => 'MW', 'code' => '+265', 'flag' => '🇲🇼'],

    // --- African countries (alphabetical) ---
    ['name' => 'Algeria',                   'iso2' => 'DZ', 'code' => '+213', 'flag' => '🇩🇿'],
    ['name' => 'Angola',                    'iso2' => 'AO', 'code' => '+244', 'flag' => '🇦🇴'],
    ['name' => 'Benin',                     'iso2' => 'BJ', 'code' => '+229', 'flag' => '🇧🇯'],
    ['name' => 'Botswana',                  'iso2' => 'BW', 'code' => '+267', 'flag' => '🇧🇼'],
    ['name' => 'Burkina Faso',              'iso2' => 'BF', 'code' => '+226', 'flag' => '🇧🇫'],
    ['name' => 'Burundi',                   'iso2' => 'BI', 'code' => '+257', 'flag' => '🇧🇮'],
    ['name' => 'Cameroon',                  'iso2' => 'CM', 'code' => '+237', 'flag' => '🇨🇲'],
    ['name' => 'Cape Verde',                'iso2' => 'CV', 'code' => '+238', 'flag' => '🇨🇻'],
    ['name' => 'Central African Republic',  'iso2' => 'CF', 'code' => '+236', 'flag' => '🇨🇫'],
    ['name' => 'Chad',                      'iso2' => 'TD', 'code' => '+235', 'flag' => '🇹🇩'],
    ['name' => 'Comoros',                   'iso2' => 'KM', 'code' => '+269', 'flag' => '🇰🇲'],
    ['name' => 'Congo (DRC)',               'iso2' => 'CD', 'code' => '+243', 'flag' => '🇨🇩'],
    ['name' => 'Congo (Republic)',          'iso2' => 'CG', 'code' => '+242', 'flag' => '🇨🇬'],
    ['name' => "Côte d'Ivoire",             'iso2' => 'CI', 'code' => '+225', 'flag' => '🇨🇮'],
    ['name' => 'Djibouti',                  'iso2' => 'DJ', 'code' => '+253', 'flag' => '🇩🇯'],
    ['name' => 'Egypt',                     'iso2' => 'EG', 'code' => '+20',  'flag' => '🇪🇬'],
    ['name' => 'Equatorial Guinea',         'iso2' => 'GQ', 'code' => '+240', 'flag' => '🇬🇶'],
    ['name' => 'Eritrea',                   'iso2' => 'ER', 'code' => '+291', 'flag' => '🇪🇷'],
    ['name' => 'Eswatini',                  'iso2' => 'SZ', 'code' => '+268', 'flag' => '🇸🇿'],
    ['name' => 'Ethiopia',                  'iso2' => 'ET', 'code' => '+251', 'flag' => '🇪🇹'],
    ['name' => 'Gabon',                     'iso2' => 'GA', 'code' => '+241', 'flag' => '🇬🇦'],
    ['name' => 'Gambia',                    'iso2' => 'GM', 'code' => '+220', 'flag' => '🇬🇲'],
    ['name' => 'Ghana',                     'iso2' => 'GH', 'code' => '+233', 'flag' => '🇬🇭'],
    ['name' => 'Guinea',                    'iso2' => 'GN', 'code' => '+224', 'flag' => '🇬🇳'],
    ['name' => 'Guinea-Bissau',             'iso2' => 'GW', 'code' => '+245', 'flag' => '🇬🇼'],
    ['name' => 'Kenya',                     'iso2' => 'KE', 'code' => '+254', 'flag' => '🇰🇪'],
    ['name' => 'Lesotho',                   'iso2' => 'LS', 'code' => '+266', 'flag' => '🇱🇸'],
    ['name' => 'Liberia',                   'iso2' => 'LR', 'code' => '+231', 'flag' => '🇱🇷'],
    ['name' => 'Libya',                     'iso2' => 'LY', 'code' => '+218', 'flag' => '🇱🇾'],
    ['name' => 'Madagascar',                'iso2' => 'MG', 'code' => '+261', 'flag' => '🇲🇬'],
    ['name' => 'Mali',                      'iso2' => 'ML', 'code' => '+223', 'flag' => '🇲🇱'],
    ['name' => 'Mauritania',                'iso2' => 'MR', 'code' => '+222', 'flag' => '🇲🇷'],
    ['name' => 'Mauritius',                 'iso2' => 'MU', 'code' => '+230', 'flag' => '🇲🇺'],
    ['name' => 'Morocco',                   'iso2' => 'MA', 'code' => '+212', 'flag' => '🇲🇦'],
    ['name' => 'Mozambique',                'iso2' => 'MZ', 'code' => '+258', 'flag' => '🇲🇿'],
    ['name' => 'Namibia',                   'iso2' => 'NA', 'code' => '+264', 'flag' => '🇳🇦'],
    ['name' => 'Niger',                     'iso2' => 'NE', 'code' => '+227', 'flag' => '🇳🇪'],
    ['name' => 'Nigeria',                   'iso2' => 'NG', 'code' => '+234', 'flag' => '🇳🇬'],
    ['name' => 'Rwanda',                    'iso2' => 'RW', 'code' => '+250', 'flag' => '🇷🇼'],
    ['name' => 'São Tomé and Príncipe',     'iso2' => 'ST', 'code' => '+239', 'flag' => '🇸🇹'],
    ['name' => 'Senegal',                   'iso2' => 'SN', 'code' => '+221', 'flag' => '🇸🇳'],
    ['name' => 'Seychelles',                'iso2' => 'SC', 'code' => '+248', 'flag' => '🇸🇨'],
    ['name' => 'Sierra Leone',              'iso2' => 'SL', 'code' => '+232', 'flag' => '🇸🇱'],
    ['name' => 'Somalia',                   'iso2' => 'SO', 'code' => '+252', 'flag' => '🇸🇴'],
    ['name' => 'South Africa',              'iso2' => 'ZA', 'code' => '+27',  'flag' => '🇿🇦'],
    ['name' => 'South Sudan',               'iso2' => 'SS', 'code' => '+211', 'flag' => '🇸🇸'],
    ['name' => 'Sudan',                     'iso2' => 'SD', 'code' => '+249', 'flag' => '🇸🇩'],
    ['name' => 'Tanzania',                  'iso2' => 'TZ', 'code' => '+255', 'flag' => '🇹🇿'],
    ['name' => 'Togo',                      'iso2' => 'TG', 'code' => '+228', 'flag' => '🇹🇬'],
    ['name' => 'Tunisia',                   'iso2' => 'TN', 'code' => '+216', 'flag' => '🇹🇳'],
    ['name' => 'Uganda',                    'iso2' => 'UG', 'code' => '+256', 'flag' => '🇺🇬'],
    ['name' => 'Zambia',                    'iso2' => 'ZM', 'code' => '+260', 'flag' => '🇿🇲'],
    ['name' => 'Zimbabwe',                  'iso2' => 'ZW', 'code' => '+263', 'flag' => '🇿🇼'],

    // --- Rest of world (alphabetical) ---
    ['name' => 'Afghanistan',               'iso2' => 'AF', 'code' => '+93',  'flag' => '🇦🇫'],
    ['name' => 'Albania',                   'iso2' => 'AL', 'code' => '+355', 'flag' => '🇦🇱'],
    ['name' => 'Argentina',                 'iso2' => 'AR', 'code' => '+54',  'flag' => '🇦🇷'],
    ['name' => 'Armenia',                   'iso2' => 'AM', 'code' => '+374', 'flag' => '🇦🇲'],
    ['name' => 'Australia',                 'iso2' => 'AU', 'code' => '+61',  'flag' => '🇦🇺'],
    ['name' => 'Austria',                   'iso2' => 'AT', 'code' => '+43',  'flag' => '🇦🇹'],
    ['name' => 'Azerbaijan',                'iso2' => 'AZ', 'code' => '+994', 'flag' => '🇦🇿'],
    ['name' => 'Bahrain',                   'iso2' => 'BH', 'code' => '+973', 'flag' => '🇧🇭'],
    ['name' => 'Bangladesh',                'iso2' => 'BD', 'code' => '+880', 'flag' => '🇧🇩'],
    ['name' => 'Belarus',                   'iso2' => 'BY', 'code' => '+375', 'flag' => '🇧🇾'],
    ['name' => 'Belgium',                   'iso2' => 'BE', 'code' => '+32',  'flag' => '🇧🇪'],
    ['name' => 'Bolivia',                   'iso2' => 'BO', 'code' => '+591', 'flag' => '🇧🇴'],
    ['name' => 'Bosnia & Herzegovina',      'iso2' => 'BA', 'code' => '+387', 'flag' => '🇧🇦'],
    ['name' => 'Brazil',                    'iso2' => 'BR', 'code' => '+55',  'flag' => '🇧🇷'],
    ['name' => 'Bulgaria',                  'iso2' => 'BG', 'code' => '+359', 'flag' => '🇧🇬'],
    ['name' => 'Cambodia',                  'iso2' => 'KH', 'code' => '+855', 'flag' => '🇰🇭'],
    ['name' => 'Canada',                    'iso2' => 'CA', 'code' => '+1',   'flag' => '🇨🇦'],
    ['name' => 'Chile',                     'iso2' => 'CL', 'code' => '+56',  'flag' => '🇨🇱'],
    ['name' => 'China',                     'iso2' => 'CN', 'code' => '+86',  'flag' => '🇨🇳'],
    ['name' => 'Colombia',                  'iso2' => 'CO', 'code' => '+57',  'flag' => '🇨🇴'],
    ['name' => 'Croatia',                   'iso2' => 'HR', 'code' => '+385', 'flag' => '🇭🇷'],
    ['name' => 'Cuba',                      'iso2' => 'CU', 'code' => '+53',  'flag' => '🇨🇺'],
    ['name' => 'Cyprus',                    'iso2' => 'CY', 'code' => '+357', 'flag' => '🇨🇾'],
    ['name' => 'Czech Republic',            'iso2' => 'CZ', 'code' => '+420', 'flag' => '🇨🇿'],
    ['name' => 'Denmark',                   'iso2' => 'DK', 'code' => '+45',  'flag' => '🇩🇰'],
    ['name' => 'Ecuador',                   'iso2' => 'EC', 'code' => '+593', 'flag' => '🇪🇨'],
    ['name' => 'Finland',                   'iso2' => 'FI', 'code' => '+358', 'flag' => '🇫🇮'],
    ['name' => 'France',                    'iso2' => 'FR', 'code' => '+33',  'flag' => '🇫🇷'],
    ['name' => 'Georgia',                   'iso2' => 'GE', 'code' => '+995', 'flag' => '🇬🇪'],
    ['name' => 'Germany',                   'iso2' => 'DE', 'code' => '+49',  'flag' => '🇩🇪'],
    ['name' => 'Greece',                    'iso2' => 'GR', 'code' => '+30',  'flag' => '🇬🇷'],
    ['name' => 'Honduras',                  'iso2' => 'HN', 'code' => '+504', 'flag' => '🇭🇳'],
    ['name' => 'Hungary',                   'iso2' => 'HU', 'code' => '+36',  'flag' => '🇭🇺'],
    ['name' => 'India',                     'iso2' => 'IN', 'code' => '+91',  'flag' => '🇮🇳'],
    ['name' => 'Indonesia',                 'iso2' => 'ID', 'code' => '+62',  'flag' => '🇮🇩'],
    ['name' => 'Iran',                      'iso2' => 'IR', 'code' => '+98',  'flag' => '🇮🇷'],
    ['name' => 'Iraq',                      'iso2' => 'IQ', 'code' => '+964', 'flag' => '🇮🇶'],
    ['name' => 'Ireland',                   'iso2' => 'IE', 'code' => '+353', 'flag' => '🇮🇪'],
    ['name' => 'Israel',                    'iso2' => 'IL', 'code' => '+972', 'flag' => '🇮🇱'],
    ['name' => 'Italy',                     'iso2' => 'IT', 'code' => '+39',  'flag' => '🇮🇹'],
    ['name' => 'Japan',                     'iso2' => 'JP', 'code' => '+81',  'flag' => '🇯🇵'],
    ['name' => 'Jordan',                    'iso2' => 'JO', 'code' => '+962', 'flag' => '🇯🇴'],
    ['name' => 'Kazakhstan',                'iso2' => 'KZ', 'code' => '+7',   'flag' => '🇰🇿'],
    ['name' => 'Kuwait',                    'iso2' => 'KW', 'code' => '+965', 'flag' => '🇰🇼'],
    ['name' => 'Kyrgyzstan',                'iso2' => 'KG', 'code' => '+996', 'flag' => '🇰🇬'],
    ['name' => 'Laos',                      'iso2' => 'LA', 'code' => '+856', 'flag' => '🇱🇦'],
    ['name' => 'Latvia',                    'iso2' => 'LV', 'code' => '+371', 'flag' => '🇱🇻'],
    ['name' => 'Lebanon',                   'iso2' => 'LB', 'code' => '+961', 'flag' => '🇱🇧'],
    ['name' => 'Lithuania',                 'iso2' => 'LT', 'code' => '+370', 'flag' => '🇱🇹'],
    ['name' => 'Luxembourg',                'iso2' => 'LU', 'code' => '+352', 'flag' => '🇱🇺'],
    ['name' => 'Malaysia',                  'iso2' => 'MY', 'code' => '+60',  'flag' => '🇲🇾'],
    ['name' => 'Malta',                     'iso2' => 'MT', 'code' => '+356', 'flag' => '🇲🇹'],
    ['name' => 'Mexico',                    'iso2' => 'MX', 'code' => '+52',  'flag' => '🇲🇽'],
    ['name' => 'Moldova',                   'iso2' => 'MD', 'code' => '+373', 'flag' => '🇲🇩'],
    ['name' => 'Mongolia',                  'iso2' => 'MN', 'code' => '+976', 'flag' => '🇲🇳'],
    ['name' => 'Montenegro',                'iso2' => 'ME', 'code' => '+382', 'flag' => '🇲🇪'],
    ['name' => 'Myanmar',                   'iso2' => 'MM', 'code' => '+95',  'flag' => '🇲🇲'],
    ['name' => 'Nepal',                     'iso2' => 'NP', 'code' => '+977', 'flag' => '🇳🇵'],
    ['name' => 'Netherlands',               'iso2' => 'NL', 'code' => '+31',  'flag' => '🇳🇱'],
    ['name' => 'New Zealand',               'iso2' => 'NZ', 'code' => '+64',  'flag' => '🇳🇿'],
    ['name' => 'Norway',                    'iso2' => 'NO', 'code' => '+47',  'flag' => '🇳🇴'],
    ['name' => 'Oman',                      'iso2' => 'OM', 'code' => '+968', 'flag' => '🇴🇲'],
    ['name' => 'Pakistan',                  'iso2' => 'PK', 'code' => '+92',  'flag' => '🇵🇰'],
    ['name' => 'Palestine',                 'iso2' => 'PS', 'code' => '+970', 'flag' => '🇵🇸'],
    ['name' => 'Panama',                    'iso2' => 'PA', 'code' => '+507', 'flag' => '🇵🇦'],
    ['name' => 'Paraguay',                  'iso2' => 'PY', 'code' => '+595', 'flag' => '🇵🇾'],
    ['name' => 'Peru',                      'iso2' => 'PE', 'code' => '+51',  'flag' => '🇵🇪'],
    ['name' => 'Philippines',               'iso2' => 'PH', 'code' => '+63',  'flag' => '🇵🇭'],
    ['name' => 'Poland',                    'iso2' => 'PL', 'code' => '+48',  'flag' => '🇵🇱'],
    ['name' => 'Portugal',                  'iso2' => 'PT', 'code' => '+351', 'flag' => '🇵🇹'],
    ['name' => 'Qatar',                     'iso2' => 'QA', 'code' => '+974', 'flag' => '🇶🇦'],
    ['name' => 'Romania',                   'iso2' => 'RO', 'code' => '+40',  'flag' => '🇷🇴'],
    ['name' => 'Russia',                    'iso2' => 'RU', 'code' => '+7',   'flag' => '🇷🇺'],
    ['name' => 'Saudi Arabia',              'iso2' => 'SA', 'code' => '+966', 'flag' => '🇸🇦'],
    ['name' => 'Serbia',                    'iso2' => 'RS', 'code' => '+381', 'flag' => '🇷🇸'],
    ['name' => 'Singapore',                 'iso2' => 'SG', 'code' => '+65',  'flag' => '🇸🇬'],
    ['name' => 'Slovakia',                  'iso2' => 'SK', 'code' => '+421', 'flag' => '🇸🇰'],
    ['name' => 'Slovenia',                  'iso2' => 'SI', 'code' => '+386', 'flag' => '🇸🇮'],
    ['name' => 'South Korea',               'iso2' => 'KR', 'code' => '+82',  'flag' => '🇰🇷'],
    ['name' => 'Spain',                     'iso2' => 'ES', 'code' => '+34',  'flag' => '🇪🇸'],
    ['name' => 'Sri Lanka',                 'iso2' => 'LK', 'code' => '+94',  'flag' => '🇱🇰'],
    ['name' => 'Sweden',                    'iso2' => 'SE', 'code' => '+46',  'flag' => '🇸🇪'],
    ['name' => 'Switzerland',               'iso2' => 'CH', 'code' => '+41',  'flag' => '🇨🇭'],
    ['name' => 'Syria',                     'iso2' => 'SY', 'code' => '+963', 'flag' => '🇸🇾'],
    ['name' => 'Taiwan',                    'iso2' => 'TW', 'code' => '+886', 'flag' => '🇹🇼'],
    ['name' => 'Tajikistan',                'iso2' => 'TJ', 'code' => '+992', 'flag' => '🇹🇯'],
    ['name' => 'Thailand',                  'iso2' => 'TH', 'code' => '+66',  'flag' => '🇹🇭'],
    ['name' => 'Turkey',                    'iso2' => 'TR', 'code' => '+90',  'flag' => '🇹🇷'],
    ['name' => 'Turkmenistan',              'iso2' => 'TM', 'code' => '+993', 'flag' => '🇹🇲'],
    ['name' => 'Ukraine',                   'iso2' => 'UA', 'code' => '+380', 'flag' => '🇺🇦'],
    ['name' => 'United Arab Emirates',      'iso2' => 'AE', 'code' => '+971', 'flag' => '🇦🇪'],
    ['name' => 'United Kingdom',            'iso2' => 'GB', 'code' => '+44',  'flag' => '🇬🇧'],
    ['name' => 'United States',             'iso2' => 'US', 'code' => '+1',   'flag' => '🇺🇸'],
    ['name' => 'Uruguay',                   'iso2' => 'UY', 'code' => '+598', 'flag' => '🇺🇾'],
    ['name' => 'Uzbekistan',                'iso2' => 'UZ', 'code' => '+998', 'flag' => '🇺🇿'],
    ['name' => 'Venezuela',                 'iso2' => 'VE', 'code' => '+58',  'flag' => '🇻🇪'],
    ['name' => 'Vietnam',                   'iso2' => 'VN', 'code' => '+84',  'flag' => '🇻🇳'],
    ['name' => 'Yemen',                     'iso2' => 'YE', 'code' => '+967', 'flag' => '🇾🇪'],
];
